export const data = [
  {
    itemCode: "SKU001",
    itemName: "Product 1",
    category: "Raw Material",
    stockLevel: 45,
    reorderLevel: 25,
    uom: "Kg",
    location: "WH 1",
    batchLot: "57559",
    expiryDate: "12/09/2025",
    status: "active",
  },
  {
    itemCode: "SKU001",
    itemName: "Product 1",
    category: "Raw Material",
    stockLevel: 45,
    reorderLevel: 25,
    uom: "Kg",
    location: "WH 1",
    batchLot: "57559",
    expiryDate: "12/09/2025",
    status: "active",
  },
  {
    itemCode: "SKU001",
    itemName: "Product 1",
    category: "Raw Material",
    stockLevel: 45,
    reorderLevel: 25,
    uom: "Kg",
    location: "WH 1",
    batchLot: "57559",
    expiryDate: "12/09/2025",
    status: "active",
  },
  {
    itemCode: "SKU001",
    itemName: "Product 1",
    category: "Raw Material",
    stockLevel: 45,
    reorderLevel: 25,
    uom: "Kg",
    location: "WH 1",
    batchLot: "57559",
    expiryDate: "12/09/2025",
    status: "active",
  },
  {
    itemCode: "SKU001",
    itemName: "Product 1",
    category: "Raw Material",
    stockLevel: 45,
    reorderLevel: 25,
    uom: "Kg",
    location: "WH 1",
    batchLot: "57559",
    expiryDate: "12/09/2025",
    status: "active",
  },
  {
    itemCode: "SKU001",
    itemName: "Product 1",
    category: "Raw Material",
    stockLevel: 45,
    reorderLevel: 25,
    uom: "Kg",
    location: "WH 1",
    batchLot: "57559",
    expiryDate: "12/09/2025",
    status: "active",
  },
];

export const cardData = [
  {
    iconSrc: "/mock/stock.png",
    title: "Stock Value",
    subtitle: "RM over 60 days",
    value: "₹ 3,17,500",
  },
  {
    iconSrc: "/mock/stock.png",
    title: "Stock Value",
    subtitle: "PM over 60 days",
    value: "₹ 1,17,500",
  },
  {
    iconSrc: "/mock/Reorder.png",
    title: "Items Below Reorder Level",
    subtitle: "",
    value: 10,
  },
  {
    iconSrc: "/mock/layer.png",
    title: "Items Out of Stock",
    subtitle: "",
    value: 25,
  },
];
